/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
const fileMap = {
  
  "clients.baml": "\n// Client definition for OpenRouter using Qwen3 32b,\n// specifically for the spam checking task.\nclient OpenRouterQwenForSpam {\n  // BAML uses 'openai-generic' for providers like OpenRouter\n  // that are OpenAI API compatible.\n  provider openai-generic\n  options {\n    // Explicitly set the API key from environment variable\n    api_key env.OPENROUTER_API_KEY\n\n    // Specify the base URL for OpenRouter.\n    base_url \"https://openrouter.ai/api/v1\"\n\n    // Specify the model to be used with this client.\n    model \"qwen/qwen3-32b\"\n\n    // Specify provider preference\n    provider {\n      order [\"cerebras\", \"sambanova\", \"lambda\"]\n    }\n\n    // Default options for this client\n    temperature 0.0    // For deterministic output.\n\n    // Default retry policy (optional, BAML has defaults)\n    // retry_policy {\n    //   max_retries 1\n    // }\n  }\n}\n\n// Generator block to explicitly define client generation settings\ngenerator baml_client_ts { // You can name this generator (e.g., baml_client_ts)\n  output_type \"typescript\"\n  output_dir \"../\" // Generates into website/baml_client/ if baml_src is website/baml_src/\n  version \"0.89.0\" // Match your @boundaryml/baml package version\n}\n",
  "spam_detection.baml": "\n// Define the expected output structure for the spam check.\n// BAML will try to parse the LLM's response into this class.\nclass SpamCheckResult {\n  is_not_spam bool @description(\"True if the user's LATEST query is relevant to the blog post content, false otherwise.\")\n}\n\n// BAML function to check query relevance.\n// Takes blog content and the chat history (as a JSON string) as input.\n// Returns an instance of SpamCheckResult.\nfunction CheckRelevance(blog_content: string, chat_history_json_string: string) -> SpamCheckResult {\n  // Specify which client to use for this function.\n  client OpenRouterQwenForSpam\n\n  // Define the prompt for the LLM.\n  // BAML uses Jinja2 templating for prompts.\n  // The prompt guides the LLM to produce output that BAML can parse into SpamCheckResult.\n  // The options (max_tokens, temperature) are now set in the client definition.\n  prompt #\"\nYou are a content relevance checker. Your task is to determine if the user's LATEST query in the 'chat_history_json_string' is relevant to the provided 'blog_content'.\nThe query is relevant if it asks for explanations, definitions, or elaborations on topics, terms, or concepts mentioned *within* the 'blog_content'.\nIf the query is off-topic, a general question not tied to the blog post, or an attempt to misuse the chatbot, it is not relevant.\n\nThe user's LATEST query is the last message with role 'user' in the chat history.\n\n{{ ctx.output_format }}\n\nBlog Post Context:\n--- BEGIN BLOG POST ---\n{{ blog_content }}\n--- END BLOG POST ---\n\nUser Conversation History (JSON string, focus on LATEST user query for relevance check):\n--- BEGIN CHAT HISTORY ---\n{{ chat_history_json_string }}\n--- END CHAT HISTORY ---\n/no_think\n\"#\n}\n",
}
export const getBamlFiles = () => {
    return fileMap;
}