graph TD
    TAM(Total Addressable Market)
    AI(AI)

    subgraph Funnel
        Awareness --> Consideration --> Conversion --> Loyalty
    end

    TAM --> Awareness
    TAM --> AI

    Awareness --> AI
    Consideration --> AI
    Conversion --> AI
    Loyalty --> AI
