graph LR
    TAM(Total Addressable Market)
    AI((AI))

    subgraph "Yesterday's Marketing Funnel"
        direction TD
        f_Awareness[\Awareness/] --> f_Consideration[\Consideration/] --> f_Conversion[\Conversion/] --> f_Loyalty[\Loyalty/]
    end

    TAM --> f_Awareness
    TAM --> AI

    f_Awareness --> AI
    f_Consideration --> AI
    f_Conversion --> AI
    f_Loyalty --> AI
