graph LR
    TAM(Total Addressable Market)
    AI((AI))

    subgraph "Yesterday's Marketing Funnel"
        direction TD
        Awareness[\Awareness/] --> Consideration[\Consideration/] --> Conversion[\Conversion/] --> Loyalty[\Loyalty/]
    end

    TAM --> Awareness
    TAM --> AI

    Awareness --> AI
    Consideration --> AI
    Conversion --> AI
    Loyalty --> AI
