%%{init: {'theme':'dark', 'themeVariables': {'background': '#212121'}}}%%
graph TD

subgraph content
ai_landing_page["Landing Page,<br/>Blogs, and News"]
www
sota_llms_knowledge
instruction_tuning_dataset
end

subgraph step_1__extract
customer_archetypes
problems
facts
end

simulated_user_question["<b>Step 2:</b><br/>Simulate a <b>question</b><br/>that a user would<br/>ask ChatGPT"]

ai_landing_page --> customer_archetypes
ai_landing_page --> problems
ai_landing_page --> facts
facts --> knowledge_graph
www --> knowledge_graph
sota_llms_knowledge --> knowledge_graph
customer_archetypes --> simulated_user_question
problems --> simulated_user_question
knowledge_graph --> simulated_user_question
simulated_user_question --> answer
knowledge_graph --> answer
simulated_user_question --> instruction_tuning_dataset
answer --> instruction_tuning_dataset
instruction_tuning_dataset --> www
instruction_tuning_dataset -->sota_llms_knowledge


style ai_landing_page stroke:#ffffff,stroke-width:4px,fill:#111111
style instruction_tuning_dataset stroke:#ffffff,stroke-width:4px,fill:#111111
