graph TD
landing_page["Landing Page,<br/>Blogs, and News"] -->indexing
indexing -->matching
search_query -->matching
matching -->list_relevant_pages

landing_page -->train_ai_brain
user_instruction -->thinking["thinking<br/>and reasoning"]
train_ai_brain -->thinking
thinking -->response

