graph LR
  style yc fill:#f0f0f0,stroke:#f0f0f0
  style pow fill:#f0f0f0,stroke:#f0f0f0
  style lp fill:#d3d3d3,stroke:#999
  style b fill:#d3d3d3,stroke:#999
  style other fill:#d3d3d3,stroke:#999
  style g fill:#d3d3d3,stroke:#999
  style h fill:#d3d3d3,stroke:#999
  style page fill:#d3d3d3,stroke:#999
  style pubhf fill:#d3d3d3,stroke:#999
  style cllm fill:#d3d3d3,stroke:#999
subgraph yc[Your Content]
  lp("Landing<br/>Page")
  b(Blogs)
  other(Other)
end
subgraph pow[Pearls of Wisdom]
  g(("Generate<br/>Instructions<br/>and Responses"))
  h(("Human Experts<br/>Peer-Review"))
end
page["Your Website<br/>(for Crawlers)"]
pubhf[("Public Dataset<br/>such as Hugging Face<br/>(for Trainers and Fine-Tunners)")]
cllm["Fine-Tune Your Own<br/>Chat-Assistant"]
lp-->g
b-->g
other-->g
g==>h
h-->page
h-->pubhf
h-->cllm
