graph LR
  style yc fill:#f0f0f0,stroke:#f0f0f0
  style pow fill:#f0f0f0,stroke:#f0f0f0
  style lp fill:#d3d3d3,stroke:#d3d3d3
  style b fill:#d3d3d3,stroke:#d3d3d3
  style other fill:#d3d3d3,stroke:#d3d3d3
  style g fill:#d3d3d3,stroke:#d3d3d3
  style h fill:#d3d3d3,stroke:#d3d3d3
  style page fill:#d3d3d3,stroke:#d3d3d3
  style pubhf fill:#d3d3d3,stroke:#d3d3d3
  style cllm fill:#d3d3d3,stroke:#d3d3d3
subgraph yc[your content]
  lp("landing<br/>page")
  b(blogs)
  other(other)
end
subgraph pow[Pearls of Wisdom]
  g(("generate<br/>instructions<br/>and responses"))
  h(("human experts<br/>peer-review"))
end
page["your website<br/>(for crawlers)"]
pubhf[("public dataset<br/>such as Hugging Face<br/>(for trainers and fine-tunners)")]
cllm["fine-tune<br/>your custom LLM"]
lp-->g
b-->g
other-->g
g==>h
h-->page
h-->pubhf
h-->cllm
