name: Generate AIK HTML

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Generate aik.html
      run: |
        python generate_aik_html.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'Kirill Igumenshchev'
        git config --global user.email 'kirill.igum@gmail.com'
        git add aik.html
        git commit -m 'chore: Generate aik.html on commit'
        git push

